CREATE VIEW crm.[Query1]
AS 
   /*Generated by SQL Server Migration Assistant for Access version 7.10.0.*/
   /*
   *   SSMA warning messages:
   *   A2SS0067: Synchronization may run with errors because column names may repeat in '*' expression. 
   *
   */

   SELECT 
      [ServiceRMA].*, 
      [Custserv].[Description], 
      [Custserv].[Solution], 
      [Custserv].[Source], 
      [Custserv].[Service Duration]
   FROM 
      [ServiceRMA] 
         INNER JOIN [Custserv] 
         ON [ServiceRMA].[ServiceID] = [Custserv].[ServiceID]
GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'CustCRM_be.[Query1]', @level0type = N'SCHEMA', @level0name = N'crm', @level1type = N'VIEW', @level1name = N'Query1';

